#!/bin/sh
set -e

# -----------------------------------------------
# Betterlytics Self-Hosted Setup Script
# -----------------------------------------------

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    printf "A .env file already exists. Overwrite? (y/N): "
    read -r OVERWRITE
    case "$OVERWRITE" in
        [yY]*) ;;
        *) echo "Aborted."; exit 0 ;;
    esac
fi

generate_secret() {
    LENGTH=$1
    tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$LENGTH"
}

# --- Prompts ---

printf "Domain name (e.g. analytics.example.com): "
read -r DOMAIN

printf "Admin email: "
read -r ADMIN_EMAIL

printf "Admin password: "
read -r ADMIN_PASSWORD

printf "Enable automatic HTTPS via Let's Encrypt? (Y/n): "
read -r HTTPS_INPUT
case "$HTTPS_INPUT" in
    [nN]*) HTTP_SCHEME=http ;;
    *) HTTP_SCHEME=https ;;
esac

HTTP_PORT=80
HTTPS_PORT=443
if [ "$HTTP_SCHEME" = "http" ]; then
    printf "HTTP port (default: 80): "
    read -r PORT_INPUT
    if [ -n "$PORT_INPUT" ]; then
        HTTP_PORT=$PORT_INPUT
    fi
fi

printf "Enable geolocation? Requires a MaxMind account. (y/N): "
read -r GEO_INPUT
case "$GEO_INPUT" in
    [yY]*) ENABLE_GEOLOCATION=true ;;
    *) ENABLE_GEOLOCATION=false ;;
esac

MAXMIND_ACCOUNT_ID="xxxxx"
MAXMIND_LICENSE_KEY="xxxxx"
if [ "$ENABLE_GEOLOCATION" = "true" ]; then
    printf "MaxMind Account ID: "
    read -r MAXMIND_ACCOUNT_ID
    printf "MaxMind License Key: "
    read -r MAXMIND_LICENSE_KEY
fi

# --- Derive values ---

if [ "$HTTP_SCHEME" = "https" ]; then
    BIND_ADDRESS="0.0.0.0"
else
    BIND_ADDRESS="127.0.0.1"
fi

# --- Generate secret base ---

SECRET_BASE=$(generate_secret 64)

# --- Write .env ---

cat > "$ENV_FILE" <<EOF
# ===========================================
# Betterlytics Self-Hosted Configuration
# Generated by setup.sh
# ===========================================

# --- Admin Account ---
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# --- General ---
DEFAULT_LANGUAGE=en
ENABLE_UPTIME_MONITORING=false

# --- Geolocation ---
ENABLE_GEOLOCATION=${ENABLE_GEOLOCATION}
MAXMIND_ACCOUNT_ID=${MAXMIND_ACCOUNT_ID}
MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}

# --- Domain ---
DOMAIN=${DOMAIN}

# --- Proxy / HTTPS ---
HTTP_SCHEME=${HTTP_SCHEME}
HTTP_PORT=${HTTP_PORT}
HTTPS_PORT=${HTTPS_PORT}
BIND_ADDRESS=${BIND_ADDRESS}

# --- Secret Base ---
SECRET_BASE=${SECRET_BASE}

EOF

# --- Write docker-compose.override.yml ---

OVERRIDE_FILE="docker-compose.override.yml"
if [ "$HTTP_SCHEME" = "https" ]; then
    cat > "$OVERRIDE_FILE" <<EOF
services:
  betterlytics-selfhost:
    ports:
      - "${BIND_ADDRESS}:${HTTPS_PORT}:443"
EOF
else
    rm -f "$OVERRIDE_FILE"
fi

echo ""
echo "Configuration written to ${ENV_FILE}"
echo ""
echo "Domain:     ${DOMAIN}"
echo "HTTPS:      ${HTTP_SCHEME}"
echo ""
echo "Next steps:"
echo "  docker compose up -d"
echo ""
