#!/bin/sh
set -e

# -----------------------------------------------
# Betterlytics Self-Hosted Setup Script
# Generates a .env file with secure random secrets
# -----------------------------------------------

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    printf "A .env file already exists. Overwrite? (y/N): "
    read -r OVERWRITE
    case "$OVERWRITE" in
        [yY]*) ;;
        *) echo "Aborted."; exit 0 ;;
    esac
fi

generate_secret() {
    LENGTH=$1
    tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$LENGTH"
}

# --- Prompts ---

printf "Domain name (e.g. analytics.example.com): "
read -r DOMAIN

printf "Email address (used for ACME/Let's Encrypt and admin account): "
read -r EMAIL

printf "Admin password: "
read -r ADMIN_PASSWORD

printf "Enable automatic HTTPS via Let's Encrypt? (y/N): "
read -r HTTPS_INPUT
case "$HTTPS_INPUT" in
    [yY]*) ENABLE_HTTPS=true ;;
    *) ENABLE_HTTPS=false ;;
esac

HTTP_PORT=80
HTTPS_PORT=443
if [ "$ENABLE_HTTPS" = "false" ]; then
    printf "HTTP port (default: 80): "
    read -r PORT_INPUT
    if [ -n "$PORT_INPUT" ]; then
        HTTP_PORT=$PORT_INPUT
    fi
fi

printf "Enable geolocation? Requires a MaxMind account. (y/N): "
read -r GEO_INPUT
case "$GEO_INPUT" in
    [yY]*) ENABLE_GEOLOCATION=true ;;
    *) ENABLE_GEOLOCATION=false ;;
esac

MAXMIND_ACCOUNT_ID="xxxxx"
MAXMIND_LICENSE_KEY="xxxxx"
if [ "$ENABLE_GEOLOCATION" = "true" ]; then
    printf "MaxMind Account ID: "
    read -r MAXMIND_ACCOUNT_ID
    printf "MaxMind License Key: "
    read -r MAXMIND_LICENSE_KEY
fi

# --- Derive values ---

if [ "$ENABLE_HTTPS" = "true" ]; then
    BIND_ADDRESS="0.0.0.0"
    PUBLIC_BASE_URL="https://${DOMAIN}"
else
    BIND_ADDRESS="127.0.0.1"
    if [ "$HTTP_PORT" = "80" ]; then
        PUBLIC_BASE_URL="http://${DOMAIN}"
    else
        PUBLIC_BASE_URL="http://${DOMAIN}:${HTTP_PORT}"
    fi
fi

# --- Generate secrets ---

CLICKHOUSE_PASSWORD=$(generate_secret 32)
CLICKHOUSE_BACKEND_PASSWORD=$(generate_secret 32)
CLICKHOUSE_DASHBOARD_PASSWORD=$(generate_secret 32)
POSTGRES_PASSWORD=$(generate_secret 32)
NEXTAUTH_SECRET=$(generate_secret 64)
TOTP_SECRET_ENCRYPTION_KEY=$(generate_secret 32)

# --- Write .env ---

cat > "$ENV_FILE" <<EOF
# ===========================================
# Betterlytics Self-Hosted Configuration
# Generated by setup.sh
# ===========================================

# --- Proxy / HTTPS ---
ENABLE_HTTPS=${ENABLE_HTTPS}
DOMAIN=${DOMAIN}
ACME_EMAIL=${EMAIL}
HTTP_PORT=${HTTP_PORT}
HTTPS_PORT=${HTTPS_PORT}
BIND_ADDRESS=${BIND_ADDRESS}

# --- Database Passwords ---
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
CLICKHOUSE_BACKEND_PASSWORD=${CLICKHOUSE_BACKEND_PASSWORD}
CLICKHOUSE_DASHBOARD_PASSWORD=${CLICKHOUSE_DASHBOARD_PASSWORD}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# --- Public URL ---
PUBLIC_BASE_URL=${PUBLIC_BASE_URL}

# --- Auth Secrets ---
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
TOTP_SECRET_ENCRYPTION_KEY=${TOTP_SECRET_ENCRYPTION_KEY}

# --- Admin Account ---
ADMIN_EMAIL=${EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# --- General ---
DEFAULT_LANGUAGE=en

# --- Geolocation ---
ENABLE_GEOLOCATION=${ENABLE_GEOLOCATION}
MAXMIND_ACCOUNT_ID=${MAXMIND_ACCOUNT_ID}
MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
EOF

echo ""
echo "Configuration written to ${ENV_FILE}"
echo ""
echo "Public URL: ${PUBLIC_BASE_URL}"
echo "HTTPS:      ${ENABLE_HTTPS}"
echo ""
echo "Next steps:"
echo "  docker compose up -d"
echo "  curl ${PUBLIC_BASE_URL}/health"
